# Generated by Django 5.2.4 on 2025-08-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenu',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sitecontent.navmenu'),
        ),
        migrations.AlterField(
            model_name='navmenu',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
