# Generated by Django 5.2.4 on 2025-08-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_navmenu_is_parent_navmenu_parent_alter_navmenu_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended image size: 1150 × 670 px', upload_to='hero/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Recommended image size: 415 × 670 px', upload_to='hero2/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
