# Generated by Django 5.2.4 on 2025-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_hero_herotwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCodeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_left', models.ImageField(help_text='Upload left image', upload_to='offers/')),
                ('image_right', models.ImageField(help_text='Upload right image', upload_to='offers/')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('validity', models.CharField(max_length=100)),
                ('coupon_code', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Orange', 'Orange')], default='Blue', max_length=10)),
            ],
        ),
    ]
