# Generated by Django 5.2.4 on 2025-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0004_couponcodeoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcodeoffer',
            name='image_left',
            field=models.ImageField(help_text='Recommended image size: 290 × 90 px', upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='couponcodeoffer',
            name='image_right',
            field=models.ImageField(help_text='Add SVG image', upload_to='offers/'),
        ),
    ]
