# Generated by Django 5.2.4 on 2025-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0005_alter_couponcodeoffer_image_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcodeoffer',
            name='image_right',
            field=models.FileField(help_text='Add SVG image', upload_to='offers/'),
        ),
    ]
