# Generated by Django 5.2.4 on 2025-08-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0007_sitesettings_address_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
