# Generated by Django 5.2.4 on 2025-08-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0008_sitesettings_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtNavMenu3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
