# Generated by Django 5.2.4 on 2025-08-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0019_product_shipping_charge_alter_product_category'),
        ('sitecontent', '0009_ftnavmenu3'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Best Seller Bicycles', max_length=120)),
                ('limit', models.PositiveIntegerField(default=10, help_text='How many products to show')),
                ('days_window', models.PositiveIntegerField(blank=True, help_text='Limit to last N days of sales (leave empty for all-time)', null=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Select one or more root categories (child categories auto-include).', related_name='best_seller_blocks', to='bicycles.category')),
            ],
            options={
                'verbose_name': 'Best Seller Block',
                'verbose_name_plural': 'Best Seller Blocks',
            },
        ),
    ]
