# Generated by Django 5.2.4 on 2025-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0019_product_shipping_charge_alter_product_category'),
        ('sitecontent', '0010_bestsellerblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('categories', models.ManyToManyField(blank=True, help_text='Select categories for this section (all descendants auto-included).', related_name='home_sections', to='bicycles.category')),
            ],
            options={
                'verbose_name': 'Home Category Section',
                'verbose_name_plural': 'Home Category Sections',
            },
        ),
    ]
