# Generated by Django 5.2.4 on 2025-07-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0005_alter_product_sku'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, to='bicycles.product'),
        ),
    ]
