# Generated by Django 5.2.4 on 2025-07-26 16:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('short_desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Short Notes')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('color', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Gold', 'Gold'), ('Sky Blue', 'Sky Blue'), ('Silver', 'Silver')], default='Black', max_length=20)),
                ('color_code', models.CharField(default='#000000', max_length=10)),
                ('age_group', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('spec_frame', models.BooleanField(default=False)),
                ('spec_fork', models.BooleanField(default=False)),
                ('spec_gears', models.BooleanField(default=False)),
                ('spec_singlespeed', models.BooleanField(default=False)),
                ('spec_brakes', models.BooleanField(default=False)),
                ('spec_dual_suspension', models.BooleanField(default=False)),
                ('spec_single_suspension', models.BooleanField(default=False)),
                ('spec_crankset', models.BooleanField(default=False)),
                ('spec_derailleur', models.BooleanField(default=False)),
                ('spec_rims', models.BooleanField(default=False)),
                ('spec_24wheel', models.BooleanField(default=False)),
                ('spec_26wheel', models.BooleanField(default=False)),
                ('spec_27_5wheel', models.BooleanField(default=False)),
                ('spec_stickers', models.BooleanField(default=False)),
                ('spec_headset', models.BooleanField(default=False)),
                ('spec_bottom_bracket', models.BooleanField(default=False)),
                ('spec_hubs', models.BooleanField(default=False)),
                ('spec_stem', models.BooleanField(default=False)),
                ('spec_seat', models.BooleanField(default=False)),
                ('spec_frame_hight', models.BooleanField(default=False)),
                ('spec_frame_hight_value', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycles.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='bicycles.product')),
            ],
        ),
    ]
