# Generated by Django 5.2.4 on 2025-07-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0002_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
