# Generated by Django 5.2.4 on 2025-07-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0003_category_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
