# Generated by Django 5.2.4 on 2025-07-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0004_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
