# Generated by Django 5.2.4 on 2025-08-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0005_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
