# Generated by Django 5.2.4 on 2025-08-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended image size: 130 × 130 px clear backgound image', null=True, upload_to='category_images/'),
        ),
    ]
