# Generated by Django 5.2.4 on 2025-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0007_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ATVs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_Accessories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_Featured_Product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bicycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_dirtbike',
            field=models.BooleanField(default=False),
        ),
    ]
