# Generated by Django 5.2.4 on 2025-08-05 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0008_product_is_atvs_product_is_accessories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_code',
        ),
        migrations.AddField(
            model_name='product',
            name='color_1_code',
            field=models.CharField(blank=True, help_text='Hex code (e.g. #FF0000)', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='product',
            name='color_1_name',
            field=models.CharField(blank=True, help_text='Color name (e.g. Red)', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='color_2_code',
            field=models.CharField(blank=True, help_text='Optional second color hex code', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AddField(
            model_name='product',
            name='color_2_name',
            field=models.CharField(blank=True, help_text='Optional second color name', max_length=30),
        ),
    ]
