# Generated by Django 5.2.4 on 2025-08-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0009_remove_product_color_remove_product_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
