# Generated by Django 5.2.4 on 2025-08-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0011_specification_productspecification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'specification'), name='unique_product_spec'),
        ),
    ]
