# Generated by Django 5.2.4 on 2025-08-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0012_productspecification_unique_product_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='spec_24wheel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_26wheel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_27_5wheel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_bottom_bracket',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_brakes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_crankset',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_derailleur',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_dual_suspension',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_fork',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_frame',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_frame_hight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_frame_hight_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_gears',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_headset',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_hubs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_rims',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_seat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_single_suspension',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_singlespeed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_stem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='spec_stickers',
        ),
    ]
