# Generated by Django 5.2.4 on 2025-08-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0015_productreview_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
