# Generated by Django 5.2.4 on 2025-08-07 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0016_alter_productreview_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_qas', to='bicycles.product')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycles.productquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'question'), name='unique_product_question')],
            },
        ),
    ]
