# Generated by Django 5.2.4 on 2025-08-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0018_product_keywords_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping cost for this product', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bicycles.category'),
        ),
    ]
