# Generated by Django 5.2.4 on 2025-08-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicycles', '0019_product_shipping_charge_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
    ]
