# Generated by Django 5.2.4 on 2025-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('full', 'Razorpay Full'), ('cod', 'COD with 20% Advance'), ('payu', 'PayU Full')], max_length=20),
        ),
    ]
