# Generated by Django 5.2.4 on 2025-08-09 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
    ]
