# Generated by Django 5.2.4 on 2025-08-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('full', 'Razorpay Full'), ('cod', 'COD with 20% Advance'), ('payu', 'PayU Full'), ('payu_upi', 'PayU UPI')], max_length=20),
        ),
    ]
