name: deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-quesecrides
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (for metadata only)
        uses: actions/checkout@v4

      - name: SSH to EC2 and run deploy.sh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: ${{  22 }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            bash /var/www/quesecrides/deploy.sh
