name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH to EC2 and run deploy.sh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          envs: DEPLOY_BRANCH
          script: |
            export BRANCH="${{ secrets.DEPLOY_BRANCH || 'main' }}"
            bash /var/www/quesecrides/deploy/deploy.sh
