name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for logs only)
        uses: actions/checkout@v4

      - name: SSH to EC2 and run deploy.sh
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            # Always use bash -lc to load proper PATH
            bash -lc '
              chmod +x /var/www/quesecrides/deploy.sh
              /var/www/quesecrides/deploy.sh
            '
